/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Report {
    char device_id[32];
    bool has_temperature;
    float temperature;
    bool has_humidity;
    float humidity;
    bool has_relay_state;
    bool relay_state;
} Report;

typedef struct _RelayCommand {
    char device_id[32];
    bool relay_state;
} RelayCommand;

typedef struct _Message {
    uint32_t msg_id; /* Upper 16 bits: timestamp, lower 16 bits: random */
    pb_size_t which_payload;
    union {
        Report report;
        RelayCommand relay_cmd;
    } payload;
} Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Report_init_default                      {"", false, 0, false, 0, false, 0}
#define RelayCommand_init_default                {"", 0}
#define Message_init_default                     {0, 0, {Report_init_default}}
#define Report_init_zero                         {"", false, 0, false, 0, false, 0}
#define RelayCommand_init_zero                   {"", 0}
#define Message_init_zero                        {0, 0, {Report_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Report_device_id_tag                     1
#define Report_temperature_tag                   2
#define Report_humidity_tag                      3
#define Report_relay_state_tag                   4
#define RelayCommand_device_id_tag               1
#define RelayCommand_relay_state_tag             2
#define Message_msg_id_tag                       1
#define Message_report_tag                       2
#define Message_relay_cmd_tag                    3

/* Struct field encoding specification for nanopb */
#define Report_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   OPTIONAL, FLOAT,    temperature,       2) \
X(a, STATIC,   OPTIONAL, FLOAT,    humidity,          3) \
X(a, STATIC,   OPTIONAL, BOOL,     relay_state,       4)
#define Report_CALLBACK NULL
#define Report_DEFAULT NULL

#define RelayCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, BOOL,     relay_state,       2)
#define RelayCommand_CALLBACK NULL
#define RelayCommand_DEFAULT NULL

#define Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   msg_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,report,payload.report),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,relay_cmd,payload.relay_cmd),   3)
#define Message_CALLBACK NULL
#define Message_DEFAULT NULL
#define Message_payload_report_MSGTYPE Report
#define Message_payload_relay_cmd_MSGTYPE RelayCommand

extern const pb_msgdesc_t Report_msg;
extern const pb_msgdesc_t RelayCommand_msg;
extern const pb_msgdesc_t Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Report_fields &Report_msg
#define RelayCommand_fields &RelayCommand_msg
#define Message_fields &Message_msg

/* Maximum encoded size of messages (where known) */
#define MESSAGES_PB_H_MAX_SIZE                   Message_size
#define Message_size                             53
#define RelayCommand_size                        35
#define Report_size                              45

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
