/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SourceType {
    SourceType_SOURCE_TYPE_NODE = 0,
    SourceType_SOURCE_TYPE_HUB = 1
} SourceType;

/* Struct definitions */
typedef struct _Hello {
    SourceType source_type;
    char device_id[32];
} Hello;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SourceType_MIN SourceType_SOURCE_TYPE_NODE
#define _SourceType_MAX SourceType_SOURCE_TYPE_HUB
#define _SourceType_ARRAYSIZE ((SourceType)(SourceType_SOURCE_TYPE_HUB+1))

#define Hello_source_type_ENUMTYPE SourceType


/* Initializer values for message structs */
#define Hello_init_default                       {_SourceType_MIN, ""}
#define Hello_init_zero                          {_SourceType_MIN, ""}

/* Field tags (for use in manual encoding/decoding) */
#define Hello_source_type_tag                    1
#define Hello_device_id_tag                      2

/* Struct field encoding specification for nanopb */
#define Hello_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    source_type,       1) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         2)
#define Hello_CALLBACK NULL
#define Hello_DEFAULT NULL

extern const pb_msgdesc_t Hello_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Hello_fields &Hello_msg

/* Maximum encoded size of messages (where known) */
#define Hello_size                               35
#define MESSAGES_PB_H_MAX_SIZE                   Hello_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
