/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_BRIDGE_NVS_PB_H_INCLUDED
#define PB_BRIDGE_NVS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Stored at key "tr-global" */
typedef struct _BridgeNvsGlobal {
    uint32_t next_endpoint_id; /* Monotonic counter for endpoint assignment */
} BridgeNvsGlobal;

/* Stored at key "tr-dev-{hex}" e.g. "tr-dev-a3f2" */
typedef struct _BridgeNvsDevice {
    char device_id[18]; /* Full device name: "vivid-falcon-a3f2" */
    uint32_t endpoint_id; /* Assigned Matter endpoint ID */
    /* Last known sensor state (optional fields) */
    bool has_temperature;
    float temperature;
    bool has_humidity;
    float humidity;
    bool has_relay_state;
    bool relay_state;
} BridgeNvsDevice;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define BridgeNvsGlobal_init_default             {0}
#define BridgeNvsDevice_init_default             {"", 0, false, 0, false, 0, false, 0}
#define BridgeNvsGlobal_init_zero                {0}
#define BridgeNvsDevice_init_zero                {"", 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BridgeNvsGlobal_next_endpoint_id_tag     1
#define BridgeNvsDevice_device_id_tag            1
#define BridgeNvsDevice_endpoint_id_tag          2
#define BridgeNvsDevice_temperature_tag          3
#define BridgeNvsDevice_humidity_tag             4
#define BridgeNvsDevice_relay_state_tag          5

/* Struct field encoding specification for nanopb */
#define BridgeNvsGlobal_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   next_endpoint_id,   1)
#define BridgeNvsGlobal_CALLBACK NULL
#define BridgeNvsGlobal_DEFAULT NULL

#define BridgeNvsDevice_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   endpoint_id,       2) \
X(a, STATIC,   OPTIONAL, FLOAT,    temperature,       3) \
X(a, STATIC,   OPTIONAL, FLOAT,    humidity,          4) \
X(a, STATIC,   OPTIONAL, BOOL,     relay_state,       5)
#define BridgeNvsDevice_CALLBACK NULL
#define BridgeNvsDevice_DEFAULT NULL

extern const pb_msgdesc_t BridgeNvsGlobal_msg;
extern const pb_msgdesc_t BridgeNvsDevice_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BridgeNvsGlobal_fields &BridgeNvsGlobal_msg
#define BridgeNvsDevice_fields &BridgeNvsDevice_msg

/* Maximum encoded size of messages (where known) */
#define BRIDGE_NVS_PB_H_MAX_SIZE                 BridgeNvsDevice_size
#define BridgeNvsDevice_size                     37
#define BridgeNvsGlobal_size                     6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
