/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Hello {
    char device_id[32];
} Hello;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Hello_init_default                       {""}
#define Hello_init_zero                          {""}

/* Field tags (for use in manual encoding/decoding) */
#define Hello_device_id_tag                      1

/* Struct field encoding specification for nanopb */
#define Hello_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1)
#define Hello_CALLBACK NULL
#define Hello_DEFAULT NULL

extern const pb_msgdesc_t Hello_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Hello_fields &Hello_msg

/* Maximum encoded size of messages (where known) */
#define Hello_size                               33
#define MESSAGES_PB_H_MAX_SIZE                   Hello_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
